version: '3'
services:
  app:
    container_name: boilerplate-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"  # Expose the debugging port
    environment:
      - ENVIRONMENT=development
      # Add more environment variables as needed
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: boilerplate-app-database
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_database_user
      - MYSQL_PASSWORD=your_database_password
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
volumes:
  mysql_data:
